-- Seçim Online: Her oyuncuya bakanlık teklifi; kabulde mevcut görevler korunur.
-- Kalıcı oyuncu/makam kayıtları değiştirilmez; yalnız yeni teklifler eklenir.
create table if not exists oyun.bakan_teklifleri (
  id bigint generated by default as identity primary key,
  bakanlik text not null references oyun.bakanliklar(kod),
  teklif_eden uuid not null references oyun.profiller(id),
  aday uuid not null references oyun.profiller(id),
  durum text not null default 'bekliyor'
    check (durum in ('bekliyor','kabul','ret','iptal')),
  zaman timestamptz not null default oyun.simdi(),
  yanit_at timestamptz
);
create unique index if not exists bakan_teklifleri_tek_bekleyen
  on oyun.bakan_teklifleri(bakanlik, aday) where durum='bekliyor';
create index if not exists bakan_teklifleri_aday_bekleyen
  on oyun.bakan_teklifleri(aday, zaman desc) where durum='bekliyor';
alter table oyun.bakan_teklifleri enable row level security;
revoke all on table oyun.bakan_teklifleri from public, anon, authenticated;
revoke all on sequence oyun.bakan_teklifleri_id_seq from public, anon, authenticated;

-- Bakanlık ek görevdir: yeni ya da mevcut diğer hiçbir makamı düşürmez.
create or replace function oyun.rol_uyumlu(a text,b text)
returns boolean language sql immutable set search_path = '' as $fn$
 select (a='bakan' or b='bakan')
    or (a=b and a in ('gb','gby'))
    or (a,b) in (
       ('mv','gby'),('gby','mv'),('gb','mv'),('mv','gb'),
       ('gb','cb'),('cb','gb'),('mv','tbmm'),('tbmm','mv'),
       ('mv','bskv'),('bskv','mv'),('mv','grup_bskv'),('grup_bskv','mv'),
       ('gby','grup_bskv'),('grup_bskv','gby')
    );
$fn$;

-- Eski doğrudan atama RPC adı uyumluluk için kalır; artık teklif gönderir.
create or replace function public.bakan_ata(p_bakanlik text,p_kad text)
returns jsonb language plpgsql security definer set search_path = '' as $fn$
declare
 p oyun.profiller := oyun.profilim();
 h oyun.profiller;
 b oyun.bakanliklar;
 t timestamptz := oyun.simdi();
 teklif_id bigint;
begin
 perform oyun.cb_zorunlu(p);
 select * into b from oyun.bakanliklar where kod=p_bakanlik;
 if b.kod is null then raise exception 'Bakanlık bulunamadı.'; end if;
 h := oyun.profil_bul(p_kad);
 if h.yasakli then raise exception 'Yasaklı hesaba teklif gönderilemez.'; end if;
 if exists(select 1 from oyun.makamlar where tur='bakan' and bakanlik=b.kod and bit is null and user_id=h.id)
 then raise exception 'Oyuncu zaten bu bakanlıkta görev yapıyor.'; end if;
 insert into oyun.bakan_teklifleri(bakanlik,teklif_eden,aday,durum,zaman)
 values(b.kod,p.id,h.id,'bekliyor',t)
 on conflict (bakanlik,aday) where durum='bekliyor'
 do update set teklif_eden=excluded.teklif_eden, zaman=excluded.zaman
 returning id into teklif_id;
 perform oyun.bildir(h.id,format('%s %s, sana %s görevi teklif etti. Bildirimler bölümünden kabul edebilir veya reddedebilirsin. Mevcut görevlerin korunacak.',oyun.yurutme_unvan(),p.kad,replace(b.ad,'Bakanlığı','Bakanlığı')),t);
 return jsonb_build_object('durum','bekliyor','teklif_id',teklif_id,'bakanlik',b.ad,'aday',h.kad);
end $fn$;

-- Oyuncu hangi görevde olursa olsun bakanlık teklifi alabilir.
create or replace function public.bakan_adaylari(p_ara text default '')
returns jsonb language plpgsql security definer set search_path = '' as $fn$
declare p oyun.profiller := oyun.profilim(); a text := lower(btrim(coalesce(p_ara,'')));
begin
 perform oyun.cb_zorunlu(p);
 return coalesce((
 select jsonb_agg(x order by (x->>'kidem')::numeric desc) from (
   select jsonb_build_object(
     'kad',pr.kad,'il',(select ad from oyun.iller where id=pr.il_id),
     'parti',oyun.parti_json(pr.parti_id),
     'kidem',oyun.kidem_puani(pr.id),
     'statu',oyun.statu_ad(oyun.statu_basamak(oyun.kidem_puani(pr.id))),
     'gorev',null,
     'bakanlik',(select b.ad from oyun.makamlar m join oyun.bakanliklar b on b.kod=m.bakanlik
       where m.user_id=pr.id and m.tur='bakan' and m.bit is null limit 1),
     'uygun',true,'engel',null
   ) x
   from oyun.profiller pr
   where not pr.yasakli
     and (a='' or lower(pr.kad) like a||'%' or lower(pr.kad) like '%'||a||'%')
   order by (lower(pr.kad) like a||'%') desc,pr.son_gorulme desc nulls last
   limit 25
 ) q),'[]'::jsonb);
end $fn$;

create or replace function public.bakan_tekliflerim()
returns jsonb language plpgsql security definer set search_path = '' as $fn$
declare p oyun.profiller := oyun.profilim();
begin
 return coalesce((
   select jsonb_agg(
     jsonb_build_object('id',x.id,'bakanlik',x.bakanlik,'bakanlik_ad',x.ad,
       'teklif_eden',x.kad,'zaman',x.zaman) order by x.zaman desc)
   from (
    select t.id,t.bakanlik,b.ad,pr.kad,t.zaman
    from oyun.bakan_teklifleri t
    join oyun.bakanliklar b on b.kod=t.bakanlik
    join oyun.profiller pr on pr.id=t.teklif_eden
    where t.aday=p.id and t.durum='bekliyor'
      and t.teklif_eden=oyun.yurutme_user()
    order by t.zaman desc limit 30
   ) x
 ),'[]'::jsonb);
end $fn$;

create or replace function public.bakan_teklif_yanit(p_teklif bigint,p_kabul boolean)
returns jsonb language plpgsql security definer set search_path = '' as $fn$
declare
 p oyun.profiller := oyun.profilim();
 t timestamptz := oyun.simdi();
 teklif oyun.bakan_teklifleri;
 b oyun.bakanliklar;
 makam record;
 eski_makam bigint;
 unvan text;
begin
 if p_kabul is null then raise exception 'Kabul veya ret seçmelisin.'; end if;
 select * into teklif from oyun.bakan_teklifleri where id=p_teklif;
 if teklif.id is null or teklif.aday<>p.id then raise exception 'Bu teklif sana ait değil.'; end if;

 -- Aynı bakanlığa paralel iki kabul işlemi yarışamaz.
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('bakan_teklif'),
                                         pg_catalog.hashtext(teklif.bakanlik));
 select * into teklif from oyun.bakan_teklifleri where id=p_teklif for update;
 if teklif.durum<>'bekliyor' then raise exception 'Bu teklif artık geçerli değil.'; end if;
 if teklif.teklif_eden is distinct from oyun.yurutme_user()
 then raise exception 'Hükümet değiştiği için bu teklif artık geçerli değil.'; end if;
 select * into b from oyun.bakanliklar where kod=teklif.bakanlik;
 unvan := oyun.yurutme_unvan();
 if not p_kabul then
   update oyun.bakan_teklifleri set durum='ret',yanit_at=t where id=teklif.id;
   perform oyun.bildir(teklif.teklif_eden,format('%s, %s bakanlığı teklifini reddetti.',p.kad,b.ad),t);
   return jsonb_build_object('durum','ret','bakanlik',b.ad);
 end if;
 if p.yasakli then raise exception 'Yasaklı hesap bakanlık görevini kabul edemez.'; end if;
 -- Yalnızca teklif verilen bakanlık devredilir; adayın diğer makamlarına dokunulmaz.
 for makam in select id,user_id from oyun.makamlar
              where tur='bakan' and bakanlik=b.kod and bit is null
 loop
   if makam.user_id=p.id then
     raise exception 'Zaten bu bakanlık görevindesin.';
   end if;
   perform oyun.makam_bitir(makam.id,t,'gorevden_alindi');
 end loop;
 insert into oyun.makamlar(tur,user_id,il_id,parti_id,bakanlik,kaynak,bas)
 values('bakan',p.id,null,p.parti_id,b.kod,'atama',t)
 returning id into eski_makam;
 update oyun.bakan_teklifleri set durum='kabul',yanit_at=t where id=teklif.id;
 update oyun.bakan_teklifleri set durum='iptal',yanit_at=t
   where bakanlik=b.kod and id<>teklif.id and durum='bekliyor';
 perform oyun.bildir(p.id,format('%s görevini kabul ettin. Diğer makamların korunuyor.',replace(b.ad,'Bakanlığı','Bakanlığı')),t);
 perform oyun.bildir(teklif.teklif_eden,format('%s, %s görevini kabul etti ve bakan olarak atandı.',p.kad,b.ad),t);
 perform oyun.olay('makam',format('%s, %s olarak atandı.',p.kad,replace(b.ad,'Bakanlığı','Bakanı')),null,p.parti_id,t);
 perform oyun.gazete_ekle('atama',format('%s''na %s atandı',b.ad,p.kad),
   format('%s, %s tarafından sunulan bakanlık teklifini kabul etti.',p.kad,unvan),
   null,t);
 return jsonb_build_object('durum','kabul','bakanlik',b.ad,'makam_id',eski_makam);
end $fn$;

revoke all on function public.bakan_ata(text,text) from public,anon;
revoke all on function public.bakan_adaylari(text) from public,anon;
revoke all on function public.bakan_tekliflerim() from public,anon;
revoke all on function public.bakan_teklif_yanit(bigint,boolean) from public,anon;
grant execute on function public.bakan_ata(text,text) to authenticated;
grant execute on function public.bakan_adaylari(text) to authenticated;
grant execute on function public.bakan_tekliflerim() to authenticated;
grant execute on function public.bakan_teklif_yanit(bigint,boolean) to authenticated;
